--- #YAML:1.0
name:                File-Next
version:             0.01
abstract:            File-finding iterator
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Andy Lester <andy@petdance.com>
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
